# Generated by Django 5.2.4 on 2025-08-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='newtype',
            options={'verbose_name': 'Yangilik Turi', 'verbose_name_plural': 'Yangilik Turlari'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=12, upload_to='news/images/', verbose_name='Asosiy rasm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='media_manage.newtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='newtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Type Name'),
        ),
    ]
