# Generated by Django 5.2.4 on 2025-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0003_documenttype_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
