# Generated by Django 5.2.4 on 2025-09-02 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0005_alter_documents_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='media_manage.newtype', verbose_name='Parent Type'),
        ),
    ]
