# Generated by Django 5.2.4 on 2025-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0008_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Video URL'),
        ),
    ]
