# Generated by Django 5.2.4 on 2025-09-13 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0009_news_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Document Title'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Document Title'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Document Title'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Document Title'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name_uz_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz_cyrl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='News Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='News Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='News Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='News Title'),
        ),
        migrations.AddField(
            model_name='newtype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
        migrations.AddField(
            model_name='newtype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
        migrations.AddField(
            model_name='newtype',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
        migrations.AddField(
            model_name='newtype',
            name='name_uz_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Type Name'),
        ),
    ]
