# Generated by Django 5.2.4 on 2025-11-22 12:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0010_documents_title_en_documents_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/files/', verbose_name='Hujjat fayli'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='media_manage.documenttype', verbose_name='Hujjat Turi'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Hujjat turi nomi'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Hujjat turi nomi'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Hujjat turi nomi'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Hujjat turi nomi'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name_uz_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Hujjat turi nomi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz_cyrl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Yangilik Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Yangilik Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Yangilik Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Yangilik Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Yangilik Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='media_manage.newtype', verbose_name='Yangilik Turi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='viewed_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='newtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='newtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Yangilik Turi Nomi'),
        ),
        migrations.AlterField(
            model_name='newtype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Yangilik Turi Nomi'),
        ),
        migrations.AlterField(
            model_name='newtype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Yangilik Turi Nomi'),
        ),
        migrations.AlterField(
            model_name='newtype',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Yangilik Turi Nomi'),
        ),
        migrations.AlterField(
            model_name='newtype',
            name='name_uz_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Yangilik Turi Nomi'),
        ),
        migrations.AlterField(
            model_name='newtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='media_manage.newtype', verbose_name='Asosiy Turi'),
        ),
    ]
