# Generated by Django 5.2.4 on 2025-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0011_alter_documents_file_alter_documents_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan vaqti'),
        ),
    ]
