# Generated by Django 5.2.4 on 2025-11-22 13:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0012_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz_cyrl',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Yangilik Matni'),
        ),
    ]
