# Generated by Django 5.2.4 on 2025-12-11 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manage', '0013_alter_news_content_alter_news_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yangilik Matni'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz_cyrl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Yangilik Matni'),
        ),
    ]
