version: "3.9"

services:
  redis:
    image: redis:7
    container_name: adu-redis
    restart: always
    ports:
      - "6379:6379"

  web:
    image: bahodir23/adu-backend:latest
    container_name: adu-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./staticfiles:/app/static
    depends_on:
      - redis