# Generated by Django 5.2.4 on 2025-08-06 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Kafedra nomi')),
                ('xmn_id', models.CharField(max_length=10, verbose_name='XMN ID')),
                ('code', models.CharField(max_length=20, verbose_name='Kod')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Pozitsiya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('xmn_id', models.CharField(max_length=30, verbose_name='XMN ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Foydalanuvchi rasmi')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Rasm URL manzili')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('year_of_enter', models.CharField(blank=True, max_length=4, null=True, verbose_name='Kirish yili')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('passport', models.CharField(blank=True, max_length=255, null=True, verbose_name="Pasport ma'lumotlari")),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('citizenship', models.CharField(choices=[('none', 'None'), ('russian', 'Russian'), ('kazakh', 'Kazakh'), ('karakalpak', 'Karakalpak'), ('tajik', 'Tajik'), ('turkmen', 'Turkmen'), ('kyrgyz', 'Kyrgyz'), ('ukrainian', 'Ukrainian'), ('belarusian', 'Belarusian'), ('armenian', 'Armenian'), ('korean', 'Korean'), ('afghan', 'Afghan'), ('uzbek', "O'zbek"), ('other', 'Boshqa')], default='uzbek', max_length=255, verbose_name='Fuqarolik')),
                ('age', models.IntegerField(default=18, verbose_name='Yosh')),
                ('employee_id_number', models.CharField(max_length=20, verbose_name='Xodim ID raqami')),
                ('meta_id', models.CharField(max_length=20, verbose_name='Meta ID')),
                ('uzkadr_id', models.CharField(max_length=10, verbose_name='UZKADR ID')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mutaxassisligi')),
                ('academicDegree', models.CharField(choices=[('10', 'Darajasiz'), ('11', 'Fan nomzodi (PhD)'), ('12', 'Fan doktori (DSc)')], default='10', max_length=255, verbose_name='Ilmiy darajasi')),
                ('academicRank', models.CharField(choices=[('10', 'Untitled'), ('11', 'Dotsent'), ('12', 'Senior Lecturer'), ('13', 'Professor')], default='10', max_length=255, verbose_name='Ilmiy unvoni')),
                ('employmentForm', models.CharField(choices=[('11', 'Asosiy ish joy'), ('13', "O'rindoshlik (tashqi)"), ('14', 'Soatbay'), ('12', "O'rindoshlik (ichki-qo'shimcha)"), ('15', "O'rindoshlik (ichki-asosiy)")], default='11', max_length=255, verbose_name='Ish shakli')),
                ('staffPosition', models.CharField(choices=[('11', "Stajor O'qituvchi"), ('12', 'Asistent'), ('13', "Katta o'qituvchi"), ('14', 'Dotsent'), ('15', 'Professor'), ('16', 'Kafedra mudiri'), ('dekan', 'Dekan'), ('dekan_assistant', 'Dekan muovini'), ('tutor', 'Tyutor'), ('engineer', '1-toifali muhandis'), ('other', 'Boshqa')], max_length=255, verbose_name='Lavozimi')),
                ('employeeType', models.CharField(choices=[('other', 'Boshqa'), ('teacher', 'Professor-o‘qituvchi xodim'), ('dekan', 'Administrativ-boshqaruv xodim'), ('tutor', 'O‘quv-yordamchi va texnik xodim')], default='teacher', max_length=255, verbose_name='Xodim turi')),
                ('is_foreign', models.BooleanField(default=False, verbose_name='Chet el fuqarosi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='DepartmentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('position', models.CharField(choices=[('11', "Stajor O'qituvchi"), ('12', 'Asistent'), ('13', "Katta o'qituvchi"), ('14', 'Dotsent'), ('15', 'Professor'), ('16', 'Kafedra mudiri'), ('dekan', 'Dekan'), ('dekan_assistant', 'Dekan muovini'), ('tutor', 'Tyutor'), ('engineer', '1-toifali muhandis'), ('other', 'Boshqa')], default='other', max_length=255, verbose_name='Lavozim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='structure.department', verbose_name='Kafedra')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_employees', to='structure.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Kafedra xodimi',
                'verbose_name_plural': 'Kafedra xodimlari',
                'db_table': 'department_employee',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Fakultet nomi')),
                ('xmn_id', models.CharField(max_length=20, verbose_name='XMN ID')),
                ('code', models.CharField(max_length=20, verbose_name='Kod')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='faculty/banner', verbose_name='Banner')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='faculty/icon', verbose_name='Ikon')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Pozitsiya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'db_table': 'faculty',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departments', to='structure.faculty', verbose_name='Fakultet'),
        ),
        migrations.CreateModel(
            name='FacultyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('position', models.CharField(choices=[('11', "Stajor O'qituvchi"), ('12', 'Asistent'), ('13', "Katta o'qituvchi"), ('14', 'Dotsent'), ('15', 'Professor'), ('16', 'Kafedra mudiri'), ('dekan', 'Dekan'), ('dekan_assistant', 'Dekan muovini'), ('tutor', 'Tyutor'), ('engineer', '1-toifali muhandis'), ('other', 'Boshqa')], default='other', max_length=255, verbose_name='Lavozim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_employees', to='structure.employee', verbose_name='Xodim')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='structure.faculty', verbose_name='Fakultet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Fakultet xodimi',
                'verbose_name_plural': 'Fakultet xodimlari',
                'db_table': 'faculty_employee',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('xmn_id', models.CharField(max_length=10, verbose_name='XMN ID')),
                ('code', models.CharField(max_length=15, verbose_name='Kod')),
                ('educationType', models.IntegerField(choices=[(11, 'Bakalavr'), (12, 'Magistr'), (13, 'Boshqa'), (14, 'Doktorantura PhD')], default=11, verbose_name="Ta'lim turi")),
                ('localityType', models.IntegerField(choices=[(10, 'Boshqa'), (11, 'Mahalliy'), (12, 'Qo‘shma'), (13, "Bo'lim")], default=11, verbose_name='Mahalliylik turi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Pozitsiya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialities', to='structure.department', verbose_name='Kafedra')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='specialities', to='structure.faculty', verbose_name='Fakultet')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'db_table': 'specialty',
            },
        ),
    ]
