# Generated by Django 5.2.4 on 2025-08-06 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_homepagetext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Universitet haqida')),
                ('students_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Talabalar soni')),
                ('teachers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name="O'qituvchilar soni")),
                ('faculty_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fakultetlar soni')),
                ('department_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kafedralar soni')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='university/', verbose_name='Rasm 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='university/', verbose_name='Rasm 2')),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': "Universitet asosiy ma'lumotlari",
                'verbose_name_plural': "Universitet asosiy ma'lumotlari",
            },
        ),
    ]
