# Generated by Django 5.2.4 on 2025-08-08 19:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_universitybaseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='admission_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField( null=True, blank=True, choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], max_length=15), size=None, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='employee',
            name='admission_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Qabul vaqti'),
        ),
    ]
