# Generated by Django 5.2.4 on 2025-08-08 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_employee_admission_dates_employee_admission_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyemployee',
            old_name='position',
            new_name='staffPosition',
        ),
        migrations.AddField(
            model_name='facultyemployee',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='admission_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], max_length=15, null=True), size=None),
        ),
    ]
