# Generated by Django 5.2.4 on 2025-08-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_fix_admission_dates_for_sqlite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDaysEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='admission_dates',
        ),
        migrations.AddField(
            model_name='employee',
            name='admission_dates',
            field=models.ManyToManyField(blank=True, to='structure.admissiondaysenum', verbose_name='Qabul kunlari'),
        ),
    ]
