# Generated by Django 5.2.4 on 2025-08-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_admissiondaysenum_remove_employee_admission_dates_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissiondaysenum',
            options={'verbose_name': 'Admission Day', 'verbose_name_plural': 'Admission Days'},
        ),
        migrations.AddField(
            model_name='admissiondaysenum',
            name='day',
            field=models.CharField(choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
