# Generated by Django 5.2.4 on 2025-08-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_alter_admissiondaysenum_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentemployee',
            name='position',
            field=models.CharField(choices=[('11', "Stajor O'qituvchi"), ('12', 'Asistent'), ('13', "Katta o'qituvchi"), ('14', 'Dotsent'), ('15', 'Professor'), ('16', 'Kafedra mudiri'), ('dekan', 'Dekan'), ('dekan_assistant', 'Dekan muovini'), ('tutor', 'Tyutor'), ('engineer', '1-toifali muhandis'), ('other', 'Boshqa'), ('rector', 'Rektor'), ('vice-rector', 'Prorektor')], default='other', max_length=255, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staffPosition',
            field=models.CharField(choices=[('11', "Stajor O'qituvchi"), ('12', 'Asistent'), ('13', "Katta o'qituvchi"), ('14', 'Dotsent'), ('15', 'Professor'), ('16', 'Kafedra mudiri'), ('dekan', 'Dekan'), ('dekan_assistant', 'Dekan muovini'), ('tutor', 'Tyutor'), ('engineer', '1-toifali muhandis'), ('other', 'Boshqa'), ('rector', 'Rektor'), ('vice-rector', 'Prorektor')], max_length=255, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='facultyemployee',
            name='staffPosition',
            field=models.CharField(choices=[('11', "Stajor O'qituvchi"), ('12', 'Asistent'), ('13', "Katta o'qituvchi"), ('14', 'Dotsent'), ('15', 'Professor'), ('16', 'Kafedra mudiri'), ('dekan', 'Dekan'), ('dekan_assistant', 'Dekan muovini'), ('tutor', 'Tyutor'), ('engineer', '1-toifali muhandis'), ('other', 'Boshqa'), ('rector', 'Rektor'), ('vice-rector', 'Prorektor')], default='other', max_length=255, verbose_name='Lavozim'),
        ),
    ]
