# Generated by Django 5.2.4 on 2025-08-25 04:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_alter_departmentemployee_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Institut nomi')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod')),
                ('division_type', models.IntegerField(choices=[(1, "Markaz/Bo'lim"), (2, 'Texnikum/Litsey')], default=1, verbose_name='Institut turi')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Tavsif')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='institution/banner', verbose_name='Banner')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='institution/icon', verbose_name='Ikon')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Pozitsiya')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('decan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='structure.employee', verbose_name='Dekan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Institut',
                'verbose_name_plural': 'Institutlar',
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('menu_type', models.CharField(choices=[('charter', 'CHARTER'), ('history', 'HISTORY'), ('council', 'UNIVERSITY_COUNCIL'), ('scientific_council', 'SCIENTIFIC_COUNCIL')], max_length=50, verbose_name='Menyu turi')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Pozitsiya')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Menyu elementi',
                'verbose_name_plural': 'Menyu elementlari',
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=150, verbose_name='Hujjat nomi')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/files/', verbose_name='Fayl')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='structure.menuitem', verbose_name='Menyu elementi')),
            ],
            options={
                'verbose_name': 'Hujjat turi',
                'verbose_name_plural': 'Hujjat turlari',
                'db_table': 'document_type',
            },
        ),
    ]
