# Generated by Django 5.2.4 on 2025-08-13 18:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_alter_departmentemployee_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tasks',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Ish vazifalari'),
        ),
    ]
