# Generated by Django 5.2.4 on 2025-08-25 05:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_divisions_menuitem_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='content_uz_cyrl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Institut nomi'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Institut nomi'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Institut nomi'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Institut nomi'),
        ),
        migrations.AddField(
            model_name='divisions',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_uz_cyrl',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='content_uz_cyrl',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Kontent'),
        ),
    ]
