# Generated by Django 5.2.4 on 2025-08-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_employee_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagetext',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='home_page/', verbose_name='Banner Image'),
        ),
    ]
