# Generated by Django 5.2.4 on 2025-08-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_divisions_content_en_divisions_content_ru_and_more'),
        ('structure', '0012_department_slug_faculty_slug_specialty_slug'),
    ]

    operations = [
    ]
