# Generated by Django 5.2.4 on 2025-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0013_merge_20250825_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('charter', 'CHARTER'), ('history', 'HISTORY'), ('council', 'UNIVERSITY_COUNCIL'), ('scientific_council', 'SCIENTIFIC_COUNCIL')], max_length=50, unique=True, verbose_name='Menyu turi'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
