# Generated by Django 5.2.4 on 2025-08-25 12:21

import apps.structure.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0014_alter_department_slug_alter_faculty_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisions',
            name='division_type',
            field=models.CharField(choices=apps.structure.enum.DivisionTypeEnum.choices, max_length=50, verbose_name='Institut turi'),
        ),
    ]
