# Generated by Django 5.2.4 on 2025-08-25 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_alter_divisions_division_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=150, verbose_name='Hujjat nomi')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/files/', verbose_name='Fayl')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='structure.divisions', verbose_name='Institut')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Institut hujjati',
                'verbose_name_plural': 'Institut hujjatlari',
                'db_table': 'division_document',
            },
        ),
    ]
