# Generated by Django 5.2.4 on 2025-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_divisiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisiondocument',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='divisiondocument',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='divisiondocument',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='divisiondocument',
            name='name_uz_cyrl',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
    ]
