# Generated by Django 5.2.4 on 2025-08-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_divisiondocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='admission_dates',
        ),
        migrations.RemoveField(
            model_name='department',
            name='xmn_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='xmn_id',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='xmn_id',
        ),
        migrations.AddField(
            model_name='divisiondocument',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='divisiondocument',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='divisiondocument',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AddField(
            model_name='divisiondocument',
            name='name_uz_cyrl',
            field=models.CharField(max_length=150, null=True, verbose_name='Hujjat nomi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='department',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Joylashuv Tartibi'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Joylashuv Tartibi'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Joylashuv Tartibi'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Joylashuv Tartibi'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.DeleteModel(
            name='AdmissionDaysEnum',
        ),
        migrations.AddField(
            model_name='employee',
            name='admission_dates',
            field=models.CharField(blank=True, help_text='Qabul kunlarini vergul bilan ajrating. Masalan: monday,tuesday,friday', max_length=255, verbose_name='Qabul kunlari'),
        ),
    ]
