# Generated by Django 5.2.4 on 2025-08-27 05:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0017_remove_employee_admission_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tasks',
        ),
        migrations.AddField(
            model_name='departmentemployee',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='facultyemployee',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
    ]
