# Generated by Django 5.2.4 on 2025-08-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0018_remove_employee_tasks_departmentemployee_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='meta_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='uzkadr_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='academicDegree',
            field=models.CharField(blank=True, choices=[('10', 'Darajasiz'), ('11', 'Fan nomzodi (PhD)'), ('12', 'Fan doktori (DSc)')], default='10', max_length=255, null=True, verbose_name='Ilmiy darajasi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='academicRank',
            field=models.CharField(blank=True, choices=[('10', 'Untitled'), ('11', 'Dotsent'), ('12', 'Senior Lecturer'), ('13', 'Professor')], default='10', max_length=255, null=True, verbose_name='Ilmiy unvoni'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Xodim ID raqami'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employmentForm',
            field=models.CharField(blank=True, choices=[('11', 'Asosiy ish joy'), ('13', "O'rindoshlik (tashqi)"), ('14', 'Soatbay'), ('12', "O'rindoshlik (ichki-qo'shimcha)"), ('15', "O'rindoshlik (ichki-asosiy)")], default='11', max_length=255, null=True, verbose_name='Ish shakli'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staffPosition',
            field=models.CharField(blank=True, choices=[('11', "Stajor O'qituvchi"), ('12', 'Asistent'), ('13', "Katta o'qituvchi"), ('14', 'Dotsent'), ('15', 'Professor'), ('16', 'Kafedra mudiri'), ('dekan', 'Dekan'), ('dekan_assistant', 'Dekan muovini'), ('tutor', 'Tyutor'), ('engineer', '1-toifali muhandis'), ('other', 'Boshqa'), ('rector', 'Rektor'), ('vice-rector', 'Prorektor')], max_length=255, null=True, verbose_name='Lavozimi'),
        ),
    ]
