# Generated by Django 5.2.4 on 2025-08-27 11:55

import apps.structure.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0019_remove_employee_meta_id_remove_employee_uzkadr_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisions',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='xmn_id',
        ),
        migrations.AlterField(
            model_name='divisions',
            name='division_type',
            field=models.CharField(choices=apps.structure.enum.DivisionTypeEnum.choices, max_length=50, verbose_name='Division turi'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Division nomi'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Division nomi'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Division nomi'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Division nomi'),
        ),
        migrations.AlterField(
            model_name='divisions',
            name='name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Division nomi'),
        ),
    ]
