# Generated by Django 5.2.4 on 2025-09-02 05:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0020_alter_divisions_options_remove_employee_xmn_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='passport',
        ),
        migrations.AddField(
            model_name='employee',
            name='task',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('structure', 'STRUCTURE'), ('charter', 'CHARTER'), ('history', 'HISTORY'), ('council', 'UNIVERSITY_COUNCIL'), ('press-secretary', 'SCIENTIFIC_COUNCIL'), ('gifted', 'STUDENTS_GIFTED'), ('tuition-fee', 'STUDENTS_TUTION_FEE'), ('management', 'STUDENTS_MANAGAMENT'), ('state-exams', 'STUDENTS_EXAMS'), ('employment', 'STUDENTS_EMPLOYEMENT'), ('data', 'EDUCATION_DATA'), ('reports', 'EDUCATION_REPORT'), ('faculty', 'EDUCATION_COLLEAGE'), ('info', 'SDG_INFO'), ('concept', 'GREEN_UNIVERSITY'), ('active-students', 'GREEN_ACTIVE_STUDENTS'), ('legal-documents', 'LEGAL_DOCUMENTS'), ('practical-activities', 'PRACTICAL_ACTIVITIES'), ('legal-acts', 'LEGAL_ACTS')], max_length=50, unique=True, verbose_name='Menyu turi'),
        ),
    ]
