# Generated by Django 5.2.4 on 2025-09-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0021_remove_employee_address_remove_employee_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('structure', 'STRUCTURE'), ('charter', 'CHARTER'), ('history', 'HISTORY'), ('council', 'UNIVERSITY_COUNCIL'), ('press-secretary', 'SCIENTIFIC_COUNCIL'), ('gifted', 'STUDENTS_GIFTED'), ('tuition-fee', 'STUDENTS_TUTION_FEE'), ('management', 'STUDENTS_MANAGAMENT'), ('state-exams', 'STUDENTS_EXAMS'), ('employment', 'STUDENTS_EMPLOYEMENT'), ('data', 'EDUCATION_DATA'), ('reports', 'EDUCATION_REPORT'), ('faculty', 'EDUCATION_COLLEAGE'), ('sdg-info', 'SDG_INFO'), ('sdg-reports', 'SDG_REPORTS'), ('concept', 'GREEN_UNIVERSITY'), ('active-students', 'GREEN_ACTIVE_STUDENTS'), ('legal-documents', 'LEGAL_DOCUMENTS'), ('practical-activities', 'PRACTICAL_ACTIVITIES'), ('legal-acts', 'LEGAL_ACTS'), ('guide', 'ADMISSION_GUIDE'), ('international', 'ADMISSION_INTERNATIONAL'), ('distance', 'ADMISSION_DISTANCE')], max_length=50, unique=True, verbose_name='Menyu turi'),
        ),
    ]
