# Generated by Django 5.2.4 on 2025-09-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0022_alter_menuitem_menu_type'),
        ('structure', '0022_employee_employeerank_alter_menuitem_menu_type'),
    ]

    operations = [
    ]
