# Generated by Django 5.2.4 on 2025-09-16 09:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0023_merge_20250915_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_uz_cyrl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagetext',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='universitybaseinfo',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='Universitet haqida'),
        ),
        migrations.AddField(
            model_name='universitybaseinfo',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Universitet haqida'),
        ),
        migrations.AddField(
            model_name='universitybaseinfo',
            name='about_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Universitet haqida'),
        ),
        migrations.AddField(
            model_name='universitybaseinfo',
            name='about_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Universitet haqida'),
        ),
        migrations.AddField(
            model_name='universitybaseinfo',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='universitybaseinfo',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='universitybaseinfo',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='universitybaseinfo',
            name='address_uz_cyrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('structure', 'STRUCTURE'), ('charter', 'CHARTER'), ('history', 'HISTORY'), ('council', 'UNIVERSITY_COUNCIL'), ('press-secretary', 'SCIENTIFIC_COUNCIL'), ('gifted', 'STUDENTS_GIFTED'), ('tuition-fee', 'STUDENTS_TUTION_FEE'), ('management', 'STUDENTS_MANAGAMENT'), ('state-exams', 'STUDENTS_EXAMS'), ('employment', 'STUDENTS_EMPLOYEMENT'), ('data', 'EDUCATION_DATA'), ('reports', 'EDUCATION_REPORT'), ('faculty', 'EDUCATION_COLLEAGE'), ('sdg-info', 'SDG_INFO'), ('sdg-reports', 'SDG_REPORTS'), ('concept', 'GREEN_UNIVERSITY'), ('active-students', 'GREEN_ACTIVE_STUDENTS'), ('legal-documents', 'LEGAL_DOCUMENTS'), ('practical-activities', 'PRACTICAL_ACTIVITIES'), ('legal-acts', 'LEGAL_ACTS'), ('guide', 'ADMISSION_GUIDE'), ('international', 'ADMISSION_INTERNATIONAL'), ('distance', 'ADMISSION_DISTANCE'), ('dormitories', 'ADMISSION_DORMITORIES')], max_length=50, unique=True, verbose_name='Menyu turi'),
        ),
    ]
