# Generated by Django 5.2.4 on 2025-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0024_employee_task_en_employee_task_ru_employee_task_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeRank_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xodim darajasi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeRank_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xodim darajasi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeRank_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xodim darajasi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeRank_uz_cyrl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xodim darajasi'),
        ),
    ]
