# Generated by Django 5.2.4 on 2025-09-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0025_employee_employeerank_en_employee_employeerank_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kafedra nomi'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Kafedra nomi'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Kafedra nomi'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Kafedra nomi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Fakultet nomi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Fakultet nomi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Fakultet nomi'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Fakultet nomi'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name="Yo'nalish nomi"),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="Yo'nalish nomi"),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="Yo'nalish nomi"),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name="Yo'nalish nomi"),
        ),
    ]
