# Generated by Django 5.2.4 on 2025-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0026_department_description_en_department_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admission_time',
            field=models.CharField(blank=True, help_text='Masalan: 09:00 - 11:00', max_length=50, null=True, verbose_name='Qabul qilingan vaqt'),
        ),
    ]
