# Generated by Django 5.2.4 on 2025-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0027_alter_employee_admission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='admission_dates_en',
            field=models.CharField(blank=True, help_text='Qabul kunlarini vergul bilan ajrating. Masalan: monday,tuesday,friday', max_length=255, null=True, verbose_name='Qabul kunlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='admission_dates_ru',
            field=models.CharField(blank=True, help_text='Qabul kunlarini vergul bilan ajrating. Masalan: monday,tuesday,friday', max_length=255, null=True, verbose_name='Qabul kunlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='admission_dates_uz',
            field=models.CharField(blank=True, help_text='Qabul kunlarini vergul bilan ajrating. Masalan: monday,tuesday,friday', max_length=255, null=True, verbose_name='Qabul kunlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='admission_dates_uz_cyrl',
            field=models.CharField(blank=True, help_text='Qabul kunlarini vergul bilan ajrating. Masalan: monday,tuesday,friday', max_length=255, null=True, verbose_name='Qabul kunlari'),
        ),
    ]
