# Generated by Django 5.2.4 on 2025-10-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0028_employee_admission_dates_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('structure', 'STRUCTURE'), ('charter', 'CHARTER'), ('history', 'HISTORY'), ('council', 'UNIVERSITY_COUNCIL'), ('press-secretary', 'UNIVERSITY_PRESS_SECRETARY'), ('gifted', 'STUDENTS_GIFTED'), ('tuition-fee', 'STUDENTS_TUTION_FEE'), ('management', 'STUDENTS_MANAGEMENT'), ('state-exams', 'STUDENTS_EXAMS'), ('employment', 'STUDENTS_EMPLOYMENT'), ('data', 'EDUCATION_DATA'), ('reports', 'EDUCATION_REPORT'), ('faculty', 'EDUCATION_COLLEAGE_FACULTY'), ('sdg-info', 'SDG_INFO'), ('sdg-reports', 'SDG_REPORTS'), ('concept', 'GREEN_UNIVERSITY_CONCEPT'), ('active-students', 'GREEN_ACTIVE_STUDENTS'), ('legal-documents', 'LEGAL_DOCUMENTS'), ('practical-activities', 'PRACTICAL_ACTIVITIES'), ('legal-acts', 'LEGAL_ACTS'), ('guide', 'ADMISSION_GUIDE'), ('international', 'ADMISSION_INTERNATIONAL'), ('distance', 'ADMISSION_DISTANCE'), ('dormitories', 'ADMISSION_DORMITORIES')], max_length=50, unique=True, verbose_name='Menyu turi'),
        ),
    ]
