# Generated by Django 5.2.4 on 2025-10-21 05:08

from django.db import migrations


def copy_full_name_to_translations(apps, schema_editor):
    Employee = apps.get_model('structure', 'Employee')
    db_alias = schema_editor.connection.alias
    for emp in Employee.objects.using(db_alias).all():
        if emp.full_name:
            emp.full_name_uz = emp.full_name
            emp.save(update_fields=['full_name_uz'])

class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0029_employee_full_name_en_employee_full_name_ru_and_more'),
    ]


    operations = [
        migrations.RunPython(copy_full_name_to_translations),
    ]