# Generated by Django 5.2.4 on 2025-10-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0030_copy_full_name_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='have_a_sub_menu',
            field=models.BooleanField(default=False),
        ),
    ]
