# Generated by Django 5.2.4 on 2025-10-27 06:34

import ckeditor.fields
from django.db import migrations

def copy_task_to_translations(apps, schema_editor):
    DepartmentEmployee = apps.get_model('structure', 'DepartmentEmployee')
    db_alias = schema_editor.connection.alias
    for emp in DepartmentEmployee.objects.using(db_alias).all():
        if hasattr(emp, 'task') and emp.task:
            emp.task_uz = emp.task
            emp.save(update_fields=['task_uz'])


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0033_alter_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentemployee',
            name='task_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='departmentemployee',
            name='task_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='departmentemployee',
            name='task_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='departmentemployee',
            name='task_uz_cyrl',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Vazifalari'),
        ),
        migrations.RunPython(copy_task_to_translations),
    ]
