# Generated by Django 5.2.4 on 2026-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0034_departmentemployee_task_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisiondocument',
            options={'ordering': ['-year', 'name'], 'verbose_name': 'Institut hujjati', 'verbose_name_plural': 'Institut hujjatlari'},
        ),
        migrations.AddField(
            model_name='divisiondocument',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Yili'),
        ),
    ]
