# Generated by Django 5.2.4 on 2025-08-05 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=150, verbose_name='Xizmat nomi')),
                ('icon', models.FileField(blank=True, null=True, upload_to='services/icons/', verbose_name='Xizmat ikonkasi (light)')),
                ('icon_dark', models.FileField(blank=True, null=True, upload_to='services/icons/', verbose_name='Xizmat ikonkasi (dark)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Xizmat haqida')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xizmatga havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Interaktiv xizmat',
                'verbose_name_plural': 'Interaktiv xizmatlar',
                'db_table': 'blog_interactive_service',
            },
        ),
    ]
