# Generated by Django 5.2.4 on 2025-08-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveservice',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xizmat haqida'),
        ),
        migrations.AddField(
            model_name='interactiveservice',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xizmat haqida'),
        ),
        migrations.AddField(
            model_name='interactiveservice',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Xizmat haqida'),
        ),
        migrations.AddField(
            model_name='interactiveservice',
            name='description_uz_cyrl',
            field=models.TextField(blank=True, null=True, verbose_name='Xizmat haqida'),
        ),
        migrations.AddField(
            model_name='interactiveservice',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Xizmat nomi'),
        ),
        migrations.AddField(
            model_name='interactiveservice',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Xizmat nomi'),
        ),
        migrations.AddField(
            model_name='interactiveservice',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Xizmat nomi'),
        ),
        migrations.AddField(
            model_name='interactiveservice',
            name='name_uz_cyrl',
            field=models.CharField(max_length=150, null=True, verbose_name='Xizmat nomi'),
        ),
    ]
