# Generated by Django 5.2.4 on 2025-08-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz_cyrl',
            field=models.CharField(max_length=255, null=True, verbose_name='Savol'),
        ),
    ]
