# Generated by Django 5.2.4 on 2025-10-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactiveservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interactiveservice',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='interactiveservice',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='interactiveservice',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='interactiveservice',
            name='description_uz_cyrl',
        ),
    ]
