# Generated by Django 5.2.4 on 2025-07-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_frontendtranslation_id_alter_versionhistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_uz_cyrl',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='versionhistory',
            name='version_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='versionhistory',
            name='version_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='versionhistory',
            name='version_uz',
            field=models.CharField(max_length=64, null=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='versionhistory',
            name='version_uz_cyrl',
            field=models.CharField(max_length=64, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='frontendtranslation',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
