# Generated by Django 5.1.1 on 2025-07-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_frontendtranslation_text_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontendtranslation',
            old_name='text_uz_cyrl',
            new_name='text_cyrl',
        ),
        migrations.RenameField(
            model_name='versionhistory',
            old_name='version_uz_cyrl',
            new_name='version_cyrl',
        ),
    ]
