# Generated by Django 5.1.1 on 2025-07-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_text_uz_cyrl_frontendtranslation_text_cyrl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontendtranslation',
            old_name='text_cyrl',
            new_name='text_uz_cyrl',
        ),
        migrations.RenameField(
            model_name='versionhistory',
            old_name='version_cyrl',
            new_name='version_uz_cyrl',
        ),
    ]
