# Generated by Django 5.2.4 on 2025-07-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_rename_text_cyrl_frontendtranslation_text_uz_cyrl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendTranslation',
        ),
        migrations.DeleteModel(
            name='VersionHistory',
        ),
    ]
